import Head from "next/head";
import { Inter } from "next/font/google";
import * as Icon from "react-bootstrap-icons";
import Timer from "./components/Timer";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [timerDays, setTimerDays] = useState();
  const [timerHours, setTimerHours] = useState();
  const [timerMinutes, setTimerMinutes] = useState();
  const [timerSeconds, setTimerSeconds] = useState();

  let interval;

  const startTimer = () => {
    const countDownDate = new Date("30 Mar, 2023").getTime();

    interval = setInterval(() => {
      const now = new Date().getTime();

      const distance = countDownDate - now;

      const days = Math.floor(distance / (24 * 60 * 60 * 1000));
      const hours = Math.floor(
        (distance % (24 * 60 * 60 * 1000)) / (1000 * 60 * 60)
      );
      const minutes = Math.floor((distance % (60 * 60 * 1000)) / (1000 * 60));
      const seconds = Math.floor((distance % (60 * 1000)) / 1000);

      if (distance < 0) {
        // Timer set 0
        clearInterval(interval.current);
      } else {
        // timer still counts
        setTimerDays(days);
        setTimerHours(hours);
        setTimerMinutes(minutes);
        setTimerSeconds(seconds);
      }
    });
  };

  useEffect(() => {
    startTimer();
  });

  return (
    <>
      <Head>
        <title>Coming soon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center items-center ">
        {/* BACKGROUND EFFECTS START */}
        <div className="bg-effects w-full h-screen overflow-hidden absolute">
          <div className="animation__scaleUp gradient__blue absolute w-[550px] h-[550px] top-10 left-[263px]"></div>
          <div className="animation__scaleUp gradient__blue absolute w-[550px] h-[550px] bottom-[-200px] right-0"></div>
          <div className="animation__scaleDown gradient__lightblue absolute w-[550px] h-[550px] right-40 top-0"></div>
          <div className="animation__scaleDown gradient__lightblue absolute w-[550px] h-[550px] bottom-0 left-[19px] "></div>
        </div>
        {/* BACKGROUND EFFECTS END */}

        <section className="flex justify-center items-center rounded-xl w-fit h-fit lg:w-[800px] lg:h-[800px] glass__bg p-2">
          <div className="flex flex-col items-center">
            {/* CARD HEADER */}
            <h1 className="text-[40px] lg:text-[64px] font-bold py-2 fl__text_dark_blue uppercase text-center">
              Coming soon
            </h1>
            <p className="text-xl fl__text_dark_blue text-center">
              Refreshed version of FlexLists is under construction, follow us
              for updates.
            </p>
            <Timer
              timerDays={timerDays}
              timerHours={timerHours}
              timerMinutes={timerMinutes}
              timerSeconds={timerSeconds}
            />
            {/* TIMER */}

            {/* NOTIFY ME */}
            <div className="flex flex-1 w-full py-4 justify-center">
              <input
                type="text"
                name=""
                id=""
                placeholder="Enter your email"
                className="h-12 w-3/5 py-4 px-2 rounded-lg border-2 border-gray-300 foucs:border-blue-400"
              />
              <button
                type="submit"
                className="h-12 ml-2 w-3/12 lg:w-1/5 fl__blue rounded-lg font-semibold text-white border-2 fl__border_blue hover:bg-transparent hover:fl__border_blue hover:fl__text_blue duration-300"
              >
                Notify me
              </button>
            </div>
            {/* SOCIAL ICONS */}
            <div className="flex flex-1 w-40 py-6 items-center justify-between">
              <Icon.Facebook className=" text-[26px] text-gray-600 cursor-pointer" />
              <Icon.Twitter className=" text-[26px] text-gray-600 cursor-pointer" />
              <Icon.Instagram className=" text-[26px] text-gray-600 cursor-pointer" />
            </div>
            <hr className="w-full border-1 border-gray-300" />
            {/* SIGN UP */}
            <div className="flex justify-start w-full pt-8">
              <p className=" m-2 fl__text_dark_blue text-xl">
                <span>Existing members login here</span>
              </p>
            </div>
            <div className="flex flex-col flex-1 w-full py-4 justify-center sm:flex-row sm:items-center">
              <input
                type="text"
                name=""
                id=""
                placeholder="Email"
                className="m-2 h-12 sm:w-5/12 py-4 px-2 mr-1 rounded-lg border-2 border-gray-300 foucs:border-blue-400"
              />
              <input
                type="text"
                name=""
                id=""
                placeholder="Password"
                className="m-2 h-12 sm:w-5/12 py-4 px-2 mr-1 rounded-lg border-2 border-gray-300 foucs:border-blue-400"
              />
              <button
                type="submit"
                className="h-12 ml-2 w-4/12 lg:w-2/12 bg-blue-500 rounded-lg font-semibold text-white  hover:fl__blue hover:text-white-500  duration-300 fl__dark_blue"
              >
                Sign in
              </button>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
